### ISSUE TITLE
output seems confusing

### ISSUE THREAD

**Issue by Geexirooz** [Osb0rn3/bugbounty-targets#2]
Hello Amir, thanks for sharing this. I checked a few commits and discovered some that were unclear. For example, the commit in [here](https://github.com/Osb0rn3/bugbounty-targets/commit/c0b1a7bc3413ebadd5355e4d794adb6b08b5265d) on `programs/bugcrowd.json` file adds and removes a json at the same time, and I'm not sure if that's how it should be.
If that's is a correct change, can you please let me know what that means?

**Comment by Osb0rn3** [comment]
> Hello Amir, thanks for sharing this. I checked a few commits and discovered some that were unclear. For example, the commit in [here](https://github.com/Osb0rn3/bugbounty-targets/commit/c0b1a7bc3413ebadd5355e4d794adb6b08b5265d) on `programs/bugcrowd.json` file adds and removes a json at the same time, and I'm not sure if that's how it should be.
> If that's is a correct change, can you please let me know what that means?

Hello! Thank you for bringing this issue to our attention. I understand that changes such as adjustments to the count of bugs or the total payments made, as well as shifts in the placement of programs within the list, may occur with each commit. Given these potential changes, I recommend that you avoid monitoring for updates solely based on commits. Instead, I suggest that you parse the JSON files and closely monitor the scopes to ensure that any changes are properly tracked and managed. Please let me know if you have any further questions or concerns - I'm here to help!

**Comment by Osb0rn3** [comment]
> Thank you for your comment. I agree that I shouldn't have relied just on commits. Now that I'm comparing the targets as lists against eachother I have come across another issue. I can explain this through the following example: In bugcrowd json file you can see something like below
> 
> ```
>         "target_groups": [
>             {
>                 "id": "15fc2b5d-25a9-4248-9d9c-b8493cd8629a",
>                 "name": "In Scope",
>                 "description_html": "",
>                 "in_scope": true,
>                 "reward_range": {},
>                 "sort_order": 0,
>                 "targets_url": "/cdt-vdp-pro/target_groups/ac38dcbd-2b53-4d43-bd8b-c89eb7b9298b/targets",
>                 "targets": [
>                     {
>                         "id": "bb5606de-3d97-453b-846b-93aa44c8c960",
>                         "name": "*.ca.gov",
>                         "description": null,
>                         "category": "website",
>                         "uri": "",
>                         "ipAddress": null,
>                         "target": {
>                             "tags": []
>                         },
>                         "sort_order": 0,
>                         "display_known_issues": false,
>                         "known_issues": {}
>                     }
>                 ]
>             }
>         ]
> ```
> 
> which means that the target (*.ca.gov) is in scope via "in_scope" key. "in_scope" would have been false if the target was out-of-scope. with that in mind I monitored Bugcrowd successfully but now I can't do the same to hackerone json file because there is no such "in-scope" to tell me whether the target is in-scope or not. This causes trouble in a way that if a new target gets added to the file I won't be able to figure out whether that's a new out-of-scope target or a new in-scope target. I have the same problem with the other two platforms (yeswehack & intigriti). Although intigriti's file gives some information about out-of-scope targets in "description" field, having a field like "in_scope" (as in bugcrowd file) would have been much better. Any help would be much appreciated.

I save all the responses I receive from platforms, which enables you to determine whether items are in-scope or out-of-scope. For instance, when using the HackerOne file, a value of 'false' for the 'eligible_for_submission' parameter indicates that the item is considered out-of-scope. This holds true for other files.
