### ISSUE TITLE
Missing: https://app.intigriti.com/researcher/programs/sqills/sqills/detail

### ISSUE THREAD

**Issue by rix4uni** [Osb0rn3/bugbounty-targets#4]
Missing: https://app.intigriti.com/researcher/programs/sqills/sqills/detail

**Comment by Osb0rn3** [comment]
Thanks for your review! I think it might be a private program
<img width="2672" alt="Screenshot 2024-08-24 at 5 42 35 PM" src="https://github.com/user-attachments/assets/7f5f39e6-6a5a-45d4-9034-2f091ce06614">
